version: "3"

services:
  ydns-updater:
    container_name: ydns_updater
    build:
        context: .
        dockerfile: Dockerfile.amd64
    environment:
        # - ENABLE_IPV4=True
        - ENABLE_IPV6=True
        - UPDATE_DELAY=30
    env_file:
        - ./domains.env
        - ./ydns.env
    restart: always
    network_mode: host
